# Generated by Django 2.1.7 on 2019-02-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfaremanagement',
            name='weeklysendamount',
            field=models.IntegerField(null=True, verbose_name='每周固定发送数额'),
        ),
    ]
