# Generated by Django 2.1.5 on 2019-01-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmanage',
            options={'managed': False, 'verbose_name': 'APP管理', 'verbose_name_plural': 'APP管理'},
        ),
        migrations.AlterModelOptions(
            name='serverlist',
            options={'managed': False, 'verbose_name': '服务器列表', 'verbose_name_plural': '服务器列表'},
        ),
        migrations.AlterModelOptions(
            name='versioninfo',
            options={'managed': False, 'verbose_name': '版本信息', 'verbose_name_plural': '版本信息'},
        ),
    ]
