# Generated by Django 2.1.7 on 2019-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0002_auto_20190215_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welfaremanagement',
            old_name='rolename',
            new_name='role_name',
        ),
        migrations.RemoveField(
            model_name='welfaremanagement',
            name='weeklysend',
        ),
        migrations.RemoveField(
            model_name='welfaremanagement',
            name='weeklysendamount',
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='is_regular',
            field=models.BooleanField(default=False, verbose_name='是否固定发放'),
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='regular_amount',
            field=models.IntegerField(null=True, verbose_name='固定发送数额'),
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='regular_period',
            field=models.IntegerField(null=True, verbose_name='固定发放周期'),
        ),
    ]
