# Generated by Django 2.1.7 on 2019-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0003_auto_20190215_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welfaremanagement',
            name='account',
        ),
        migrations.RemoveField(
            model_name='welfaremanagement',
            name='regular_amount',
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='approve_date',
            field=models.DateTimeField(null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='游戏平台'),
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='游戏区服'),
        ),
        migrations.AlterField(
            model_name='welfaremanagement',
            name='amount',
            field=models.IntegerField(verbose_name='申请数额'),
        ),
    ]
