# Generated by Django 2.1.7 on 2019-02-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0004_auto_20190215_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPlatformCfg',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField(blank=True, db_column='GID', null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PID', null=True)),
                ('pname', models.CharField(blank=True, db_column='PName', max_length=50, null=True)),
                ('createdate', models.DateField(blank=True, db_column='CreateDate', null=True)),
                ('onlinedate', models.DateField(blank=True, db_column='OnlineDate', null=True)),
                ('offlinedate', models.DateField(blank=True, db_column='OfflineDate', null=True)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=50, null=True)),
            ],
            options={
                'verbose_name': '平台配置',
                'verbose_name_plural': '平台配置',
                'db_table': 'App_Platform_cfg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, db_column='SID', null=True)),
                ('sname', models.CharField(blank=True, db_column='SName', max_length=512, null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PID', null=True)),
                ('gid', models.IntegerField(blank=True, db_column='GID', null=True)),
                ('apid', models.IntegerField(blank=True, db_column='APID', null=True)),
                ('display', models.IntegerField(blank=True, db_column='Display', null=True)),
                ('devid', models.IntegerField(blank=True, db_column='DevID', null=True)),
                ('dn', models.CharField(blank=True, db_column='DN', max_length=50, null=True)),
                ('vid', models.IntegerField(blank=True, db_column='VID', null=True)),
                ('type', models.IntegerField(blank=True, db_column='Type', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('prostatus', models.IntegerField(blank=True, db_column='ProStatus', null=True)),
                ('opendate', models.DateField(db_column='OpenDate')),
                ('mergedate', models.DateField(db_column='MergeDate')),
                ('mergeid', models.IntegerField(db_column='MergeID')),
                ('mergeidx', models.IntegerField(db_column='MergeIdx')),
                ('serverid', models.IntegerField(blank=True, db_column='ServerID', null=True)),
                ('gslist', models.CharField(blank=True, db_column='GSList', max_length=50, null=True)),
                ('dbsvr_in', models.CharField(blank=True, db_column='DBSvr_in', max_length=50, null=True)),
                ('dbname_in', models.CharField(blank=True, db_column='DBName_in', max_length=50, null=True)),
                ('dbqueryid_in', models.IntegerField(blank=True, db_column='DBQueryId_in', null=True)),
                ('dbsvr_out', models.CharField(blank=True, db_column='DBSvr_out', max_length=50, null=True)),
                ('dbname_out', models.CharField(blank=True, db_column='DBName_out', max_length=50, null=True)),
                ('dbqueryid_out', models.IntegerField(blank=True, db_column='DBQueryId_out', null=True)),
                ('serverpath', models.CharField(blank=True, db_column='ServerPath', max_length=50, null=True)),
                ('smport', models.IntegerField(db_column='SMPort')),
                ('loginport', models.CharField(blank=True, db_column='LoginPort', max_length=50, null=True)),
                ('rmbport', models.IntegerField(blank=True, db_column='RmbPort', null=True)),
                ('db_svrcfg', models.CharField(blank=True, max_length=50, null=True)),
                ('db_player', models.CharField(blank=True, max_length=50, null=True)),
                ('db_login', models.CharField(blank=True, max_length=50, null=True)),
                ('db_super', models.CharField(blank=True, max_length=50, null=True)),
                ('db_rmb', models.CharField(blank=True, max_length=50, null=True)),
                ('db_param', models.CharField(blank=True, max_length=50, null=True)),
                ('trigger_flag', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '应用服务器',
                'verbose_name_plural': '应用服务器',
                'db_table': 'App_Server_List',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='welfaremanagement',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='welfaremanagement',
            name='zone',
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='pid',
            field=models.IntegerField(default=1, verbose_name='游戏平台'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='zid',
            field=models.IntegerField(default=1, verbose_name='游戏区服'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='welfaremanagement',
            name='applicant',
            field=models.CharField(default=1, max_length=100, verbose_name='申请人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='welfaremanagement',
            name='status',
            field=models.IntegerField(choices=[(0, '审核中、'), (1, '已通过'), (2, '未通过')], default=0, verbose_name='审核状态'),
        ),
    ]
