# Generated by Django 2.1.7 on 2019-02-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0005_auto_20190216_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfaremanagement',
            name='pname',
            field=models.CharField(default=1, max_length=100, verbose_name='游戏平台名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='zname',
            field=models.CharField(default=1, max_length=100, verbose_name='游戏区服名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='welfaremanagement',
            name='approver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='welfaremanagement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='welfaremanagement',
            name='pid',
            field=models.IntegerField(verbose_name='游戏平台id'),
        ),
        migrations.AlterField(
            model_name='welfaremanagement',
            name='zid',
            field=models.IntegerField(verbose_name='游戏区服id'),
        ),
    ]
