# Generated by Django 2.1.7 on 2019-02-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0006_auto_20190216_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welfaremanagement',
            old_name='applicant',
            new_name='applicant_name',
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='applicant_id',
            field=models.IntegerField(default=1, verbose_name='申请人id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='welfaremanagement',
            name='status',
            field=models.IntegerField(default=0, verbose_name='审核状态'),
        ),
    ]
