# Generated by Django 2.1.7 on 2019-02-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0007_auto_20190219_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welfaremanagement',
            old_name='approver',
            new_name='approver_name',
        ),
        migrations.AddField(
            model_name='welfaremanagement',
            name='approver_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='审批人id'),
        ),
    ]
