# Generated by Django 2.1.7 on 2019-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0008_auto_20190219_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePlayerManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(verbose_name='游戏平台id')),
                ('pname', models.CharField(max_length=100, verbose_name='游戏平台名')),
                ('zid', models.IntegerField(verbose_name='游戏区服id')),
                ('zname', models.CharField(max_length=100, verbose_name='游戏区服名')),
                ('role_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='角色名')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用人姓名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('manager_id', models.IntegerField(verbose_name='配置者id')),
                ('manager_name', models.IntegerField(verbose_name='配置者姓名')),
            ],
            options={
                'verbose_name': '人员角色管理',
                'verbose_name_plural': '人员角色管理',
            },
        ),
    ]
