# Generated by Django 2.1.7 on 2019-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0009_roleplayermanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayermanagement',
            name='role_name',
            field=models.CharField(default=1, max_length=100, verbose_name='角色名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roleplayermanagement',
            name='user_name',
            field=models.CharField(default=1, max_length=100, verbose_name='使用人姓名'),
            preserve_default=False,
        ),
    ]
