# Generated by Django 2.1.7 on 2019-02-19 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0010_auto_20190219_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleplayermanagement',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='roleplayermanagement',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='roleplayermanagement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleplayermanagement',
            name='creator_id',
            field=models.IntegerField(default=1, verbose_name='创建者id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleplayermanagement',
            name='creator_name',
            field=models.CharField(default=1, max_length=100, verbose_name='创建者姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleplayermanagement',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
