# Generated by Django 2.1.7 on 2019-04-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ro_operations', '0012_remove_roleplayermanagement_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appserverlist',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='appserverlist',
            table='App_Server_list',
        ),
    ]
